-- BLNK customer app orders + BLNK Balance checkout
create table if not exists public.store_products(id text primary key,name text not null,price numeric(12,2) not null check(price>=0),active boolean not null default true,updated_at timestamptz not null default now());
alter table public.store_products enable row level security; revoke all on public.store_products from anon,authenticated;
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),order_number text unique not null,customer_id uuid not null references auth.users(id),total numeric(12,2) not null check(total>=0),payment_method text not null default 'wallet',status text not null default 'preparing' check(status in ('preparing','ready_to_ship','shipped','out_for_delivery','delivered','cancelled')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id text not null,product_name text not null,size text,color text,quantity integer not null check(quantity>0),unit_price numeric(12,2) not null check(unit_price>=0));
alter table public.orders enable row level security; alter table public.order_items enable row level security;
drop policy if exists "orders self select" on public.orders; create policy "orders self select" on public.orders for select to authenticated using(customer_id=auth.uid());
drop policy if exists "order items self select" on public.order_items; create policy "order items self select" on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.customer_id=auth.uid()));
create or replace function public.admin_sync_store_products(p_products jsonb) returns void language plpgsql security definer set search_path=public as $$ declare x jsonb; begin if not public.is_admin() then raise exception 'FORBIDDEN'; end if; for x in select * from jsonb_array_elements(p_products) loop insert into public.store_products(id,name,price,active,updated_at) values(x->>'id',coalesce(x->>'name','BLNK'),greatest(0,(x->>'price')::numeric),coalesce((x->>'active')::boolean,true),now()) on conflict(id) do update set name=excluded.name,price=excluded.price,active=excluded.active,updated_at=now(); end loop; end $$;
grant execute on function public.admin_sync_store_products(jsonb) to authenticated;
create or replace function public.customer_checkout(p_items jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_uid uuid:=auth.uid(); v_order uuid:=gen_random_uuid(); v_number text:='ORD-'||to_char(now(),'YYYYMMDD-HH24MISS')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,4)); v_total numeric:=0; x jsonb; v_price numeric; v_name text; v_stock integer; v_qty integer; begin if v_uid is null then raise exception 'LOGIN_REQUIRED'; end if; if p_items is null or jsonb_array_length(p_items)=0 then raise exception 'EMPTY_CART'; end if; for x in select * from jsonb_array_elements(p_items) loop v_qty:=(x->>'qty')::integer; if v_qty<1 then raise exception 'INVALID_QTY'; end if; select sp.price,sp.name into v_price,v_name from public.store_products sp where sp.id=x->>'id' and sp.active=true; if v_price is null then raise exception 'PRODUCT_NOT_AVAILABLE'; end if; select stock into v_stock from public.inventory where product_id=x->>'id' for update; if v_stock is null or v_stock<v_qty then raise exception 'OUT_OF_STOCK: %',v_name; end if; v_total:=v_total+(v_price*v_qty); end loop; update public.profiles set balance=balance-v_total,updated_at=now() where id=v_uid and balance>=v_total; if not found then raise exception 'INSUFFICIENT_BALANCE'; end if; insert into public.orders(id,order_number,customer_id,total,payment_method,status) values(v_order,v_number,v_uid,v_total,'wallet','preparing'); for x in select * from jsonb_array_elements(p_items) loop v_qty:=(x->>'qty')::integer; select sp.price,sp.name into v_price,v_name from public.store_products sp where sp.id=x->>'id'; insert into public.order_items(order_id,product_id,product_name,size,color,quantity,unit_price) values(v_order,x->>'id',v_name,x->>'size',x->>'color',v_qty,v_price); update public.inventory set stock=stock-v_qty,updated_at=now() where product_id=x->>'id'; insert into public.inventory_movements(product_id,quantity,movement_type,reference_id) values(x->>'id',-v_qty,'online_order',v_order::text); end loop; insert into public.wallet_transactions(customer_id,amount,type,description,reference_type,reference_id) values(v_uid,-v_total,'purchase','BLNK app order','order',v_order::text); return jsonb_build_object('order_id',v_order,'order_number',v_number,'total',v_total,'status','preparing'); end $$;
revoke all on function public.customer_checkout(jsonb) from public; grant execute on function public.customer_checkout(jsonb) to authenticated;
create or replace function public.admin_orders() returns table(id uuid,order_number text,customer_id uuid,customer_name text,phone text,customer_code text,total numeric,status text,created_at timestamptz) language sql security definer set search_path=public as $$ select o.id,o.order_number,o.customer_id,p.full_name,p.phone,p.customer_code,o.total,o.status,o.created_at from public.orders o join public.profiles p on p.id=o.customer_id where public.is_admin() order by o.created_at desc $$;
grant execute on function public.admin_orders() to authenticated;
create or replace function public.admin_set_order_status(p_order_id uuid,p_status text) returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_admin() then raise exception 'FORBIDDEN'; end if; if p_status not in ('preparing','ready_to_ship','shipped','out_for_delivery','delivered','cancelled') then raise exception 'INVALID_STATUS'; end if; update public.orders set status=p_status,updated_at=now() where id=p_order_id; end $$;
grant execute on function public.admin_set_order_status(uuid,text) to authenticated;


-- Current live catalog seed. Admin catalog sync will keep this table authoritative.
insert into public.store_products(id,name,price,active,updated_at) values('everyday-shorts','Everyday t-shirt',350,true,now()) on conflict(id) do update set name=excluded.name,price=excluded.price,active=excluded.active,updated_at=now();
