/* BLNK customer account — Supabase-backed customer hub */
(function(){
 const $=s=>document.querySelector(s), money=v=>`EGP ${Number(v||0).toLocaleString('en-US')}`;
 let sb=null, session=null;
 async function config(){const r=await fetch('/api/public-config',{cache:'no-store'});if(!r.ok)throw new Error('Customer accounts are not configured yet.');return r.json()}
 async function boot(){
  try{const c=await config();if(!c.supabaseUrl||!c.supabasePublishableKey)throw new Error('Customer accounts are not configured yet.');
   sb=window.supabase.createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true}});
   const x=await sb.auth.getSession();session=x.data.session;render();sb.auth.onAuthStateChange((_e,s)=>{session=s;render()});
  }catch(e){$('#accountState').innerHTML='<div class="account-empty">جاري تجهيز حسابات BLNK للعملاء.</div>'}
 }
 function authView(){return `<div class="account-auth"><div><p class="eyebrow">BLNK ACCOUNT</p><h2>حسابك في BLNK</h2><p>سجّل دخولك أو اعمل حساب جديد وكمّل ملف ستايلك.</p></div><form id="loginForm"><input name="email" type="email" placeholder="البريد الإلكتروني" required><input name="password" type="password" placeholder="كلمة المرور" minlength="6" required><button class="button button-dark" type="submit">تسجيل الدخول</button><button class="button button-light" id="showSignup" type="button">إنشاء حساب جديد</button><p id="authMsg"></p></form><form id="signupForm" class="signup-style-form" hidden><h3>إنشاء حساب + ملف الستايل</h3><div class="profile-grid"><label>الاسم<input required name="full_name"></label><label>رقم الواتساب<input required name="phone" placeholder="01xxxxxxxxx"></label><label>البريد الإلكتروني<input required name="email" type="email"></label><label>كلمة المرور<input required name="password" type="password" minlength="6"></label><label>المدينة / المنطقة<input name="city"></label><label>السن<select name="age_range"><option>18–24</option><option>25–34</option><option>35–44</option><option>45+</option></select></label><label>المقاس المعتاد<select name="size"><option>S</option><option>M</option><option>L</option><option>XL</option><option>XXL</option></select></label><label>القَصّة المفضلة<select name="fit"><option>Regular</option><option>Oversized</option><option>Slim</option><option>Relaxed</option></select></label><label>الستايل الأساسي<select name="style"><option>Minimal</option><option>Casual</option><option>Street</option><option>Smart Casual</option><option>Classic</option></select></label><label>الألوان المفضلة<input name="favorite_colors" placeholder="Black, White, Grey"></label><label>ألوان مش بتحبها<input name="disliked_colors"></label><label>استخدامك الأساسي<select name="occasion"><option>Everyday</option><option>Work</option><option>Going Out</option><option>Travel</option><option>Events</option></select></label><label>أكتر فئة بتدور عليها<select name="categories"><option>T-shirts</option><option>Shirts</option><option>Pants</option><option>Shorts</option><option>Complete outfits</option></select></label><label>ميزانية القطعة<select name="budget"><option>Under 500 EGP</option><option>500–750 EGP</option><option>750–1000 EGP</option><option>1000+ EGP</option></select></label><label>مقاس الجزمة<input name="shoe_size" placeholder="40 / 41 / 42"></label><label class="wide">إيه اللي ناقص دولابك؟<textarea name="wardrobe_gap" rows="2"></textarea></label><label class="wide">ملاحظات<textarea name="style_notes" rows="2"></textarea></label></div><button class="button button-dark" type="submit">إنشاء حساب BLNK</button><button class="button button-light" id="backLogin" type="button">عندي حساب بالفعل</button><p id="signupMsg"></p></form></div>`}
 async function dashboard(){
  const uid=session.user.id;
  const [p,i,w,o]=await Promise.all([
   sb.from('profiles').select('*').eq('id',uid).maybeSingle(),
   sb.from('invoices').select('*,invoice_items(*)').eq('customer_id',uid).order('created_at',{ascending:false}),
   sb.from('wallet_transactions').select('*').eq('customer_id',uid).order('created_at',{ascending:false}).limit(20),
   sb.from('orders').select('*,order_items(*)').eq('customer_id',uid).order('created_at',{ascending:false})
  ]);
  const profile=p.data||{}, invoices=i.data||[], wallet=w.data||[], orders=o.data||[];
  const items=invoices.flatMap(x=>x.invoice_items||[]);
  $('#accountState').innerHTML=`<div class="account-top"><div><p class="eyebrow">BLNK CLUB</p><h2>${profile.full_name||session.user.email}</h2><p class="customer-code">${profile.customer_code||'BLNK MEMBER'}</p></div><button id="logoutBtn" class="button button-light">تسجيل خروج</button></div>
  <div class="account-cards"><article><span>الرصيد</span><strong>${money(profile.balance)}</strong></article><article><span>النقاط</span><strong>${Number(profile.points||0).toLocaleString()}</strong></article><article><span>الفواتير</span><strong>${invoices.length}</strong></article><article><span>القطع المشتراة</span><strong>${items.reduce((s,x)=>s+Number(x.quantity||1),0)}</strong></article></div>
  <div class="account-grid"><section><h3>آخر الفواتير</h3>${invoices.length?invoices.slice(0,8).map(x=>`<div class="account-row"><div><b>#${x.invoice_number}</b><small>${new Date(x.created_at).toLocaleDateString('ar-EG')}</small></div><strong>${money(x.total)}</strong></div>`).join(''):'<p class="muted">لسه مفيش فواتير.</p>'}</section>
  <section><h3>مشترياتي</h3>${items.length?items.slice(0,12).map(x=>`<div class="account-row"><div><b>${x.product_name}</b><small>${[x.size,x.color].filter(Boolean).join(' / ')}</small></div><strong>×${x.quantity||1}</strong></div>`).join(''):'<p class="muted">مشترياتك هتظهر هنا بعد ربط الـPOS.</p>'}</section>
  <section><h3>شحن BLNK Balance</h3><div class="account-profile"><p><b>InstaPay:</b> 01062292012</p><p><b>Vodafone Cash:</b> 01062292012</p><p><b>Orange Cash:</b> 01222583477 / 01204107338</p></div><form id="topupForm" class="profile-grid"><label>طريقة التحويل<select name="method"><option value="instapay">InstaPay</option><option value="vodafone_cash">Vodafone Cash</option><option value="orange_cash">Orange Cash</option></select></label><label>المبلغ<input name="amount" type="number" min="1" required></label><label>الرقم اللي حولت منه<input name="sender_number" required placeholder="01xxxxxxxxx"></label><label>رقم العملية / المرجع<input name="transaction_reference" required></label><button class="button button-dark wide" type="submit">إرسال طلب شحن الرصيد</button><p id="topupMsg" class="wide"></p></form></section><section><h3>حركة الرصيد</h3>${wallet.length?wallet.map(x=>`<div class="account-row"><div><b>${x.description||x.type}</b><small>${new Date(x.created_at).toLocaleDateString('ar-EG')}</small></div><strong>${Number(x.amount)>0?'+':''}${money(x.amount)}</strong></div>`).join(''):'<p class="muted">لسه مفيش حركات على الرصيد.</p>'}</section>
  <section><h3>طلباتي من التطبيق</h3>${orders.length?orders.map(x=>{const labels={preparing:'جاري التجهيز',ready_to_ship:'جاهز للشحن',shipped:'تم الشحن',out_for_delivery:'خرج للتسليم',delivered:'تم التسليم',cancelled:'ملغي'};return `<div class="account-row"><div><b>#${x.order_number}</b><small>${new Date(x.created_at).toLocaleDateString('ar-EG')} · ${labels[x.status]||x.status}</small></div><strong>${money(x.total)}</strong></div>`}).join(''):'<p class="muted">لسه مفيش طلبات من التطبيق.</p>'}</section><section><h3>بياناتي</h3><div class="account-profile"><p><b>الموبايل:</b> ${profile.phone||'—'}</p><p><b>المستوى:</b> ${profile.club_tier||'Member'}</p><p><b>QR / Customer ID:</b> ${profile.customer_code||'—'}</p></div></section>
  <section class="style-profile-card"><h3>ملف الستايل</h3><div id="styleProfileView"></div><button id="editStyleBtn" class="button button-light" type="button">تعديل ملف الستايل</button></section></div>`;
  const sp=profile.style_profile||{};
  const labels={age_range:'السن',size:'المقاس',fit:'القَصّة',style:'الستايل',favorite_colors:'الألوان المفضلة',disliked_colors:'ألوان غير مفضلة',occasion:'الاستخدام',categories:'الفئة المفضلة',budget:'الميزانية',shoe_size:'مقاس الجزمة',wardrobe_gap:'الناقص في الدولاب',notes:'ملاحظات'};
  const view=$('#styleProfileView');
  view.innerHTML=Object.entries(labels).map(([k,l])=>`<p><b>${l}:</b> ${sp[k]||'—'}</p>`).join('');
  $('#editStyleBtn').onclick=()=>{view.innerHTML=`<form id="editStyleForm" class="profile-grid"><label>المقاس<input name="size" value="${sp.size||''}"></label><label>القَصّة<input name="fit" value="${sp.fit||''}"></label><label>الستايل<input name="style" value="${sp.style||''}"></label><label>الألوان المفضلة<input name="favorite_colors" value="${sp.favorite_colors||''}"></label><label>الاستخدام<input name="occasion" value="${sp.occasion||''}"></label><label>الفئة المفضلة<input name="categories" value="${sp.categories||''}"></label><label>الميزانية<input name="budget" value="${sp.budget||''}"></label><label>مقاس الجزمة<input name="shoe_size" value="${sp.shoe_size||''}"></label><label class="wide">الناقص في الدولاب<textarea name="wardrobe_gap">${sp.wardrobe_gap||''}</textarea></label><label class="wide">ملاحظات<textarea name="notes">${sp.notes||''}</textarea></label><button class="button button-dark wide" type="submit">حفظ التعديلات</button></form>`;$('#editStyleForm').onsubmit=async e=>{e.preventDefault();const d=new FormData(e.currentTarget),next={...sp};for(const [k,v] of d.entries())next[k]=v;const {error}=await sb.rpc('update_my_style_profile',{p_style_profile:next});if(error){alert('تعذر حفظ التعديلات.');return}await dashboard()}};
  const tf=$('#topupForm');if(tf)tf.onsubmit=async e=>{e.preventDefault();const d=new FormData(tf),m=$('#topupMsg');m.textContent='جاري إرسال الطلب...';const {error}=await sb.rpc('request_balance_topup',{p_method:d.get('method'),p_amount:Number(d.get('amount')),p_sender_number:d.get('sender_number'),p_transaction_reference:d.get('transaction_reference')});m.textContent=error?'تعذر إرسال الطلب: '+error.message:'تم إرسال طلب الشحن للإدارة. الرصيد هيضاف بعد مراجعة التحويل.';if(!error)tf.reset()};$('#logoutBtn').onclick=()=>sb.auth.signOut();
 }
 async function render(){if(!session){$('#accountState').innerHTML=authView();const login=$('#loginForm'),signup=$('#signupForm'),msg=$('#authMsg');$('#showSignup').onclick=()=>{login.hidden=true;signup.hidden=false};$('#backLogin').onclick=()=>{signup.hidden=true;login.hidden=false};login.onsubmit=async e=>{e.preventDefault();const d=new FormData(login);const {error}=await sb.auth.signInWithPassword({email:d.get('email'),password:d.get('password')});msg.textContent=error?'بيانات الدخول غير صحيحة.':''};signup.onsubmit=async e=>{e.preventDefault();const d=new FormData(signup),sm=$('#signupMsg');sm.textContent='جاري إنشاء حسابك...';const style_profile={age_range:d.get('age_range'),size:d.get('size'),fit:d.get('fit'),style:d.get('style'),favorite_colors:d.get('favorite_colors'),disliked_colors:d.get('disliked_colors'),occasion:d.get('occasion'),categories:d.get('categories'),budget:d.get('budget'),shoe_size:d.get('shoe_size'),wardrobe_gap:d.get('wardrobe_gap'),notes:d.get('style_notes')};const {data,error}=await sb.auth.signUp({email:d.get('email'),password:d.get('password'),options:{data:{full_name:d.get('full_name'),phone:d.get('phone'),city:d.get('city'),style_profile}}});sm.textContent=error?error.message:(data.session?'تم إنشاء الحساب وملف الستايل.':'تم إنشاء الحساب. افتح رسالة تأكيد البريد ثم سجّل الدخول.');};return}await dashboard()}
 window.BLNKAccount={
  getSession:()=>session,
  reserveTryOn:async(productId)=>{
    if(!sb||!session) throw new Error('LOGIN_REQUIRED');
    const {data,error}=await sb.rpc('reserve_tryon',{p_product_id:String(productId||'')});
    if(error) throw error;
    return data;
  },
  completeTryOn:async(id)=>{if(!sb||!session)return;const {error}=await sb.rpc('complete_tryon',{p_transaction_id:id});if(error)throw error;},
  refundTryOn:async(id)=>{if(!sb||!session)return;const {error}=await sb.rpc('refund_tryon',{p_transaction_id:id});if(error)throw error;},
  checkout:async(items)=>{if(!sb||!session)throw new Error('LOGIN_REQUIRED');const {data,error}=await sb.rpc('customer_checkout',{p_items:items});if(error)throw error;await dashboard();return data;}
 };
 document.addEventListener('DOMContentLoaded',boot);
})();