const GITHUB_API='https://api.github.com';
const REPO='mediabogy-hue/tito-store';
const FILE_PATH='customers.json';
const headers=()=>({Authorization:`Bearer ${process.env.GITHUB_TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'});
async function readDb(){const r=await fetch(`${GITHUB_API}/repos/${REPO}/contents/${FILE_PATH}`,{headers:headers()});if(!r.ok)throw Error('Could not read customer database');const f=await r.json();return {items:JSON.parse(Buffer.from(f.content,'base64').toString('utf8')),sha:f.sha};}
async function writeDb(items,sha,message){const r=await fetch(`${GITHUB_API}/repos/${REPO}/contents/${FILE_PATH}`,{method:'PUT',headers:headers(),body:JSON.stringify({message,content:Buffer.from(JSON.stringify(items,null,2)+'\n').toString('base64'),sha,branch:'main'})});if(!r.ok)throw Error('Could not save customer database');}
function admin(req){return process.env.ADMIN_KEY&&String(req.headers['x-admin-key']||'')===String(process.env.ADMIN_KEY);}
function newId(){return `BLNK-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;}
export default async function handler(req,res){try{if(!process.env.GITHUB_TOKEN)return res.status(500).json({error:'GITHUB_TOKEN is not configured'});if(req.method==='POST'){const b=req.body||{};if(!String(b.name||'').trim()||!String(b.phone||'').trim())return res.status(400).json({error:'Name and phone are required'});const db=await readDb();const customer={customerId:newId(),name:String(b.name).trim(),phone:String(b.phone).trim(),balance:0,bonus:0,createdAt:new Date().toISOString(),profile:b.profile||{},ledger:[]};db.items.push(customer);await writeDb(db.items,db.sha,'Add BLNK customer profile');return res.status(201).json(customer);}if(req.method==='GET'){if(!admin(req))return res.status(401).json({error:'Unauthorized'});const id=String(req.query?.id||'').trim();if(!id)return res.status(400).json({error:'Customer ID required'});const db=await readDb();const c=db.items.find(x=>x.customerId===id);if(!c)return res.status(404).json({error:'Customer not found'});return res.status(200).json(c);}return res.status(405).json({error:'Method not allowed'});}catch(e){return res.status(500).json({error:e.message})}}
